import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Controle de clientes - Novo Usuário",
    description: "Generated by create next app",
};

export default function NovoUsuarioLayoutPage({ children }: { children: React.ReactNode }) {
    return (
        <>
            {children}
        </>
    );
};